//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FXA.DPSE.Service.TraceTracking.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ElectronicTraceTracking
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ElectronicTraceTracking()
        {
            this.ElectronicTraceTrackingDetails = new HashSet<ElectronicTraceTrackingDetail>();
        }
    
        public long Id { get; set; }
        public string RequestId { get; set; }
        public string ChannelType { get; set; }
        public string ClientSessionId { get; set; }
        public string ClientDeviceId { get; set; }
        public string ClientIpAddressV4 { get; set; }
        public int ChequeCount { get; set; }
        public int TotalTransactionAmount { get; set; }
        public string DepositAccountName { get; set; }
        public string DepositAccountNumber { get; set; }
        public string DepositAccountBsbCode { get; set; }
        public string DepositAccountType { get; set; }
        public System.DateTime DateTimeCreated { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ElectronicTraceTrackingDetail> ElectronicTraceTrackingDetails { get; set; }
    }
}
