//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FXA.DPSE.Service.TraceTracking.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ElectronicTraceTrackingDetail
    {
        public long Id { get; set; }
        public long ElectronicTraceTrackingId { get; set; }
        public string ChequeTraceTrackingCode { get; set; }
    
        public virtual ElectronicTraceTracking ElectronicTraceTracking { get; set; }
    }
}
