//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FXA.DPSE.Service.TraceTracking.DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TraceTrackingDb : DbContext
    {
        public TraceTrackingDb()
            : base("name=TraceTrackingDb")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ElectronicTraceTracking> ElectronicTraceTrackings { get; set; }
        public virtual DbSet<ElectronicTraceTrackingDetail> ElectronicTraceTrackingDetails { get; set; }
    }
}
