//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FXA.DPSE.Service.ShadowPost.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShadowPost
    {
        public long Id { get; set; }
        public string TrackingId { get; set; }
        public System.Guid RequestGuid { get; set; }
        public string SessionId { get; set; }
        public string DeviceId { get; set; }
        public string IpAddressV4 { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
    }
}
