//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FXA.DPSE.Service.Audit.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Audit
    {
        public long Id { get; set; }
        public string TrackingIdentifier { get; set; }
        public string ExternalCorrelationIdentifier { get; set; }
        public string DocumentReferenceNumber { get; set; }
        public System.DateTimeOffset AuditDateTime { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Resource { get; set; }
        public string ChannelType { get; set; }
        public string MachineName { get; set; }
        public string ServiceName { get; set; }
        public string OperationName { get; set; }
        public string OperatorName { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
    }
}
