//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FXA.DPSE.Service.DipsTransport.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransmissionBatch
    {
        public long TransmissionId { get; set; }
        public long PaymentInstructionId { get; set; }
        public string BatchNumber { get; set; }
        public string FilePath { get; set; }
        public string FileName { get; set; }
        public Nullable<int> TransactionCount { get; set; }
    
        public virtual Transmission Transmission { get; set; }
    }
}
