CREATE TABLE [dbo].[PayloadDetails]
(
	[Id] BIGINT NOT NULL IDENTITY(1,1), 
    [PayloadId] BIGINT NOT NULL, 
    [ElectronicTraceTrackingId] BIGINT NOT NULL,
	CONSTRAINT FK_Payload FOREIGN KEY (PayloadId) REFERENCES Payloads(Id),
	CONSTRAINT [PK_PayloadDetails] PRIMARY KEY CLUSTERED 
	(
		[Id] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]