//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FXA.DPSE.Service.DipsPayload.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Voucher
    {
        public long Id { get; set; }
        public long PaymentInstructionId { get; set; }
        public string TrackingId { get; set; }
        public int SequenceId { get; set; }
        public string VoucherType { get; set; }
        public string TransactionCode { get; set; }
        public string AuxDom { get; set; }
        public System.DateTime ProcessingDateTime { get; set; }
        public string BSB { get; set; }
        public string AccountNumber { get; set; }
        public int AmountInCents { get; set; }
        public bool IsNonPostingCheque { get; set; }
    
        public virtual PaymentInstruction PaymentInstruction { get; set; }
        public virtual VoucherImage VoucherImage { get; set; }
    }
}
